
# SEO settings
title: "From"
title2: "Undefined" # default: ""
description: "Another insight to developer's issues.."
keywords: "leonel, goncalves, download, SEO, blog, web, minimalist, thinkspace"
url: http://leonelgoncalves.com/ # site url
cover: assets/images/fromUndefined.png
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-100568449-2
repo: https://github.com/leonelgoncalves/leonelgoncalves.github.io
disqus_url: "leonelgoncalves"
disqus_shortname: "leonelgoncalves"
github_username:  "leonelgoncalves"
comments: true
future: true
# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Leonel Goncalves"
  job      : "Software Engineer"
  bio      : "Perfection is not attainable, but if we chase perfection we can catch excellence."
  email    : liongoncalves@gmail.com
  thumb    : /images/author.jpg
  url      : http://leonelgoncalves.com/
  facebook : https://www.facebook.com/leonel.goncalves1
  linkedin : https://www.linkedin.com/in/leonel-goncalves

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About

exclude: ["drafts", "gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
